### ISSUE TITLE
创建缓存文件名的时候,能不能忽略视频连接后面的参数的啊?

### ISSUE THREAD

**Issue by callmewenxi** [ksvc/ksyhttpcache_ios#14]
创建缓存文件名的时候,能不能忽略视频连接后面的参数的啊?点击一个视频,每次点击的参数都不一样,导致缓存无法使用 =.= 
http://xxxxxxx/35c513f702aa9a1f33b9bbae1c8836f1.mp4?xxxxxxxxxxx
就是忽略问号❓后面的那部分…

**Comment by shixiaoda** [comment]
+1 建议这些配置方面的东西 开源出来

**Comment by FirmianaRain** [comment]
相应功能会尽快安排开发

**Comment by fpzeng** [comment]
https://github.com/ksvc/ksyhttpcache_ios/releases/tag/v1.2.2
已经支持，请试用
