### ISSUE TITLE
咱们暂时还没有自动播放下一个视频的API接口？

### ISSUE THREAD

**Issue by lwb22853628** [ksvc/ksyhttpcache_ios#16]

**Comment by mayudong1** [comment]
这种功能应该是播放器的逻辑吧  
弄个播放列表，在上一个播放结束之后开启下一个的播放  
如果是使用我们的播放sdk的话，在播放结束时会有个通知，在这个通知里使用reset和seturl的方式更新url，然后播放，就可以实现播放列表的功能  
可以参考 https://github.com/ksvc/KSYMediaPlayer_iOS/wiki/oneInstance

**Comment by fpzeng** [comment]
cache proxy只提供cache功能，自动播放请调用播放器接口
