### ISSUE TITLE
crash in [ActionWorker notifyDownloadProgress]

### ISSUE THREAD

**Issue by yykingking123** [ksvc/ksyhttpcache_ios#3]
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
(
	0   CoreFoundation                      0x00000001881e21d8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000186c1c55c objc_exception_throw + 56
	2   CoreFoundation                      0x00000001880c6c3c <redacted> + 364
	3   CoreFoundation                      0x00000001880c6aac <redacted> + 64
	4   ****                                0x0000000102a80b7c -[ActionWorker notifyDownloadProgress] + 656
	5   ****                                0x0000000102a800d8 -[ActionWorker processActionsWithHandler:] + 392
	6   ****                                0x0000000102a8173c -[ActionWorker URLSession:task:didCompleteWithError:] + 556
	7   ****                                0x0000000102a7eae4 -[URLSessionDelegateObject URLSession:task:didCompleteWithError:] + 172
	8   CFNetwork                           0x00000001889969f8 <redacted> + 72
	9   Foundation                          0x0000000188ca6754 <redacted> + 16
	10  Foundation                          0x0000000188beb2c8 <redacted> + 96
	11  Foundation                          0x0000000188bdb8c4 <redacted> + 620
	12  Foundation                          0x0000000188ca8b00 <redacted> + 228
	13  libdispatch.dylib                   0x00000001074d521c _dispatch_client_callout + 16
	14  libdispatch.dylib                   0x00000001074e2b54 _dispatch_queue_serial_drain + 1136
	15  libdispatch.dylib                   0x00000001074d8ce4 _dispatch_queue_invoke + 672
	16  libdispatch.dylib                   0x00000001074e4e6c _dispatch_root_queue_drain + 584
	17  libdispatch.dylib                   0x00000001074e4bb8 _dispatch_worker_thread3 + 140
	18  libsystem_pthread.dylib             0x00000001872762b8 _pthread_wqthread + 1288
	19  libsystem_pthread.dylib             0x0000000187275da4 start_wqthread + 4

**Comment by sunyazhou13** [comment]
已经fix 请使用最新版本
