### ISSUE TITLE
crash   [__NSArrayM cacheWorker]:

### ISSUE THREAD

**Issue by ClaudeLi** [ksvc/ksyhttpcache_ios#5]
[MediaDownloader setURL:contentInfo:]  在iOS8 iPhone5上carsh， 在iOS10的6s上是好的 希望可以解决

**Comment by sunyazhou13** [comment]
谢谢 提供建议 我这边找个 iPhone5测试一下 尽快修复

**Comment by sunyazhou13** [comment]
已经修复 请更新最新版本测试 感谢支持

**Comment by ClaudeLi** [comment]
👌 谢谢
