### ISSUE TITLE
您好，URL能否加入加密识别。

### ISSUE THREAD

**Issue by zbleftover** [ksvc/ksyhttpcache_ios#8]
我们的视频是在服务端进行加密的，每次请求到的视频地址都是带有参数，如下：@"http://qnfile.quanmintaiji.cn/video/vip/class5_01.mp4?e=1500033947&token=OCVYUjOc1OK-b1uGAd-mkl6mzBLkMBVyO31xYg6P:blXuiu_J2h3b1czRPeblgSrA4qE="

其中，从开头到mp4的url都是固定的，从？后面每次的参数都不同。该库每次都识别为不同的url，也就不能使用缓存。

**Comment by zbleftover** [comment]
请问官方人员能否支持，我们这边比较急，如果不支持我只能找新的框架了

**Comment by fpzeng** [comment]
正在开发，需要点时间。

**Comment by fpzeng** [comment]
https://github.com/ksvc/ksyhttpcache_ios/releases/tag/v1.2.2
已经支持，请试用
