### ISSUE TITLE
AVPlayer可以使用吗？

### ISSUE THREAD

**Issue by ceekay1991** [ksvc/ksyhttpcache_ios#9]
AVPlayer可以使用吗？

**Comment by fpzeng** [comment]
可以啊

**Comment by ceekay1991** [comment]
看你们的framework,视频缓存是使用的VIMediaCache吧?HTTPServer 是有重写CocoaHTTPServer吗，为什么要打到framework里？

**Comment by fpzeng** [comment]
已经改用dependency，请见podspec
https://github.com/ksvc/ksyhttpcache_ios/blob/master/ksyhttpcache.podspec
